# Generated by Django 3.0.4 on 2020-03-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('EmailId', models.EmailField(max_length=200)),
                ('HighUser', models.BooleanField(default=False)),
                ('DateTime', models.DateTimeField()),
            ],
        ),
    ]
