# Generated by Django 3.0.4 on 2020-05-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='key',
        ),
    ]
