# Generated by Django 3.0.4 on 2020-05-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_remove_role_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='role_diabetes',
        ),
    ]
