# Generated by Django 3.0.4 on 2020-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20200331_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes',
            name='Outcome',
            field=models.IntegerField(default=2),
        ),
    ]
