# Generated by Django 3.0.4 on 2020-05-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20200501_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_diabetes',
            new_name='role_dia',
        ),
        migrations.AddField(
            model_name='role',
            name='role_heart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calc.heart'),
        ),
    ]
