# Generated by Django 3.0.4 on 2020-05-01 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0004_auto_20200501_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_heart',
        ),
        migrations.AddField(
            model_name='role',
            name='User_mail',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_dia',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='calc.diabetes'),
        ),
    ]
