# Generated by Django 3.0.4 on 2020-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20200501_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='User_mail',
            field=models.IntegerField(),
        ),
    ]
