# Generated by Django 3.0.4 on 2020-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20200502_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_dia',
            field=models.IntegerField(),
        ),
    ]
